import type { Metadata } from "next";


import NavBar from "@/app/ui/navbar";
import Footer from "@/app/ui/footer";


export const metadata: Metadata = {
  title: "Trum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <NavBar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
